ticketTypes = {'A1': {'ticketDescription': 'First leg of repo-euro master sales',
  'ticketType': 'Repo Euro Conversions'},
 'AE': {'ticketDescription': 'Auto sales execution',
  'ticketType': 'Auto-Execution'},
 'ALG': {'ticketDescription': 'Alleged trade', 'ticketType': 'SSEOMS'},
 'AP': {'ticketDescription': 'Repo product type allocation',
  'ticketType': 'Repo Euro Conversions'},
 'ARC': {'ticketDescription': 'Allocated repo cash ticket',
  'ticketType': 'Repos'},
 'AT': {'ticketDescription': 'Agency trader ticket', 'ticketType': 'SSEOMS'},
 'BCA': {'ticketDescription': 'Broker commission adjustment',
  'ticketType': 'Other'},
 'BNC': {'ticketDescription': 'Bunched record', 'ticketType': 'SSEOMS'},
 'BS': {'ticketDescription': 'Buy-Sellback master ticket',
  'ticketType': 'Repos'},
 'BSA': {'ticketDescription': 'Buy-sellback allocation',
  'ticketType': 'Repos'},
 'BT': {'ticketDescription': 'Bunch trade ticket', 'ticketType': 'SSEOMS'},
 'CA': {'ticketDescription': 'Corporate action trade (added offline)',
  'ticketType': 'Corporate Action'},
 'CAB': {'ticketDescription': 'Commission allocation breakdown (COMA)',
  'ticketType': 'Other'},
 'CAE': {'ticketDescription': 'Corrected auto sales execution',
  'ticketType': 'Auto-Execution'},
 'CALC': {'ticketDescription': 'Buyside called record type',
  'ticketType': 'Repo Euro Conversions'},
 'CAP': {'ticketDescription': 'Corrected repo product type allocation',
  'ticketType': 'Repo Euro Conversions'},
 'CAR': {'ticketDescription': 'Corrected repo allocation cash ticket',
  'ticketType': 'Repos'},
 'CAT': {'ticketDescription': 'Corrected agency trader ticket',
  'ticketType': 'SSEOMS'},
 'CBS': {'ticketDescription': 'Corrected buy-sellback master ticket',
  'ticketType': 'Repos'},
 'CBS*': {'ticketDescription': 'Corected partial buy-sellback master ticket',
  'ticketType': 'Repos'},
 'CBSA': {'ticketDescription': 'Corrected buy-sellback allocation',
  'ticketType': 'Repos'},
 'CC': {'ticketDescription': 'Converted money-market commitment',
  'ticketType': 'Money Markets'},
 'CCA': {'ticketDescription': 'Corrected corporate action trade',
  'ticketType': 'Corporate Action'},
 'CCC': {'ticketDescription': 'Corrected cash compensation transaction',
  'ticketType': 'Euro Conversion'},
 'CCMS': {'ticketDescription': 'Corrected corrected money-market commitment buy slate',
  'ticketType': 'Money Markets'},
 'CCO': {'ticketDescription': 'Corrected carry-over slate',
  'ticketType': 'Slates'},
 'CCP': {'ticketDescription': 'Corrected converted settled position',
  'ticketType': 'Euro Conversion'},
 'CCS': {'ticketDescription': 'Corrected near leg FX swap ticket',
  'ticketType': 'Swaps'},
 'CCT': {'ticketDescription': 'Corrected carry-over sales ticket',
  'ticketType': 'Sales'},
 'CE2': {'ticketDescription': 'Corrected second leg of repo-euro',
  'ticketType': 'Repo Euro Conversions'},
 'CEU': {'ticketDescription': 'Corrected Euro ticket',
  'ticketType': 'Euro Conversion'},
 'CEX': {'ticketDescription': 'Corrected sales execution',
  'ticketType': 'Auto-Execution'},
 'CFS': {'ticketDescription': 'Corrected far leg FX swap ticket',
  'ticketType': 'Swaps'},
 'CFT': {'ticketDescription': 'Corrected futures ticket',
  'ticketType': 'Futures'},
 'CJL': {'ticketDescription': 'Corrected journal trade',
  'ticketType': 'Journal Trades'},
 'CLPL': {'ticketDescription': 'Sellside called record type',
  'ticketType': 'Repo Euro Conversions'},
 'CLT': {'ticketDescription': 'Corrected LATT ticket',
  'ticketType': 'LATT Transfers'},
 'CM': {'ticketDescription': 'Closed repo slate ticket',
  'ticketType': 'Repos'},
 'CMC': {'ticketDescription': 'Corrected money-market commitment',
  'ticketType': 'Money Markets'},
 'CMR': {'ticketDescription': 'Corrected repo master cash ticket',
  'ticketType': 'Repos'},
 'CMS': {'ticketDescription': 'Corrected money-market commitment buy slate',
  'ticketType': 'Money Markets'},
 'CMT': {'ticketDescription': 'Corrected matched ticket',
  'ticketType': 'Ticket Matching'},
 'CMT*': {'ticketDescription': 'Unallocated or partially unallocated CMT',
  'ticketType': 'Ticket Matching'},
 'CO': {'ticketDescription': 'Completed sales order', 'ticketType': 'SSEOMS'},
 'COA': {'ticketDescription': 'Corrected order management allocation ticket',
  'ticketType': 'Order Management'},
 'COMS': {'ticketDescription': 'Corrected order management master ticket',
  'ticketType': 'Order Management'},
 'COP': {'ticketDescription': 'Carry-over pending ticket',
  'ticketType': 'Auto-Execution'},
 'COS': {'ticketDescription': 'Carry-over slate', 'ticketType': 'Slates'},
 'COT': {'ticketDescription': 'Carry-over sales ticket',
  'ticketType': 'Sales'},
 'CP*': {'ticketDescription': 'Partially allocated corrected master ticket (XPT)',
  'ticketType': 'Portfolio Allocations'},
 'CPA': {'ticketDescription': 'Corrected portfolio allocation ticket',
  'ticketType': 'Portfolio Allocations'},
 'CPL': {'ticketDescription': 'Corrected mortgage pool transaction',
  'ticketType': 'Mortgage / TBAs'},
 'CPM': {'ticketDescription': 'Corrected portfolio master ticket',
  'ticketType': 'Portfolio Allocations'},
 'CPM*': {'ticketDescription': 'Partially allocated corrected master ticket',
  'ticketType': 'Portfolio Allocations'},
 'CPN': {'ticketDescription': 'Coupon payment ticket',
  'ticketType': 'Mortgage / TBAs'},
 'CPP': {'ticketDescription': 'Completed pending ticket',
  'ticketType': 'Auto-Execution'},
 'CPR': {'ticketDescription': 'Completed repo sales ticket',
  'ticketType': 'Repos'},
 'CPS': {'ticketDescription': 'Completed slate', 'ticketType': 'Slates'},
 'CPT': {'ticketDescription': 'Completed sales ticket', 'ticketType': 'Sales'},
 'CPX': {'ticketDescription': 'Corrected pending auto-ex transaction',
  'ticketType': 'Auto-Execution'},
 'CR': {'ticketDescription': 'Closed repo ticket', 'ticketType': 'Repos'},
 'CRA': {'ticketDescription': 'Corrected repo trader allocation',
  'ticketType': 'Repo Euro Conversions'},
 'CRF': {'ticketDescription': 'Corrected offline ticket',
  'ticketType': 'Consolidate Message Feed'},
 'CRS': {'ticketDescription': 'Corrected repo money slate',
  'ticketType': 'Repos'},
 'CRT': {'ticketDescription': 'Corrected repo ticket with collateral',
  'ticketType': 'Repos'},
 'CS': {'ticketDescription': 'Corrected slate', 'ticketType': 'Slates'},
 'CSA': {'ticketDescription': 'Corrected sales allocation ticket',
  'ticketType': 'Sales'},
 'CSB': {'ticketDescription': 'Corrected sales MT allocation piece',
  'ticketType': 'Sales'},
 'CSB*': {'ticketDescription': 'Corrected partial sell-buyback master ticket',
  'ticketType': 'Repos'},
 'CSBA': {'ticketDescription': 'Corrected sell-buyback allocation',
  'ticketType': 'Repos'},
 'CSH': {'ticketDescription': 'Cash added/removed from portfolio',
  'ticketType': 'Cash'},
 'CSJL': {'ticketDescription': 'Closeout swap journal ticket',
  'ticketType': 'Swaps'},
 'CSM': {'ticketDescription': 'Corrected sales master ticket',
  'ticketType': 'Sales'},
 'CSM*': {'ticketDescription': 'Corrected partial sales master ticket',
  'ticketType': 'Sales'},
 'CSO': {'ticketDescription': 'Corrected sales order', 'ticketType': 'SSEOMS'},
 'CST': {'ticketDescription': 'Corrected sales ticket', 'ticketType': 'Sales'},
 'CSW': {'ticketDescription': 'Closeout swap ticket', 'ticketType': 'Swaps'},
 'CTB': {'ticketDescription': 'Completely allocated TBA',
  'ticketType': 'Mortgage / TBAs'},
 'CTT': {'ticketDescription': 'Corrected trader ticket',
  'ticketType': 'Trader Tickets'},
 'CV': {'ticketDescription': 'Conversion trade (for WI conversions)',
  'ticketType': 'Other'},
 'CWT': {'ticketDescription': 'Corrected web feed tickets',
  'ticketType': 'Other'},
 'DIV': {'ticketDescription': 'Equity dividend ticket', 'ticketType': 'Other'},
 'E1': {'ticketDescription': 'First leg of repo-euro conversion (national currency)',
  'ticketType': 'Repo Euro Conversions'},
 'E2': {'ticketDescription': 'Second leg of repo-euro conversion (euro currency)',
  'ticketType': 'Repo Euro Conversions'},
 'ECC': {'ticketDescription': 'Cash compensation transaction',
  'ticketType': 'Euro Conversion'},
 'EST': {'ticketDescription': 'Euro-converted slate', 'ticketType': 'Slates'},
 'EUR': {'ticketDescription': 'Reinstate ticket in Euro',
  'ticketType': 'Euro Conversion'},
 'EX': {'ticketDescription': 'Sales execution',
  'ticketType': 'Auto-Execution'},
 'FCS': {'ticketDescription': 'Far leg FX swap ticket', 'ticketType': 'Swaps'},
 'FSP': {'ticketDescription': 'Closeout settled position in national currency',
  'ticketType': 'Euro Conversion'},
 'FT': {'ticketDescription': 'Futures ticket', 'ticketType': 'Futures'},
 'JL': {'ticketDescription': 'Journal trade', 'ticketType': 'Journal Trades'},
 'KA': {'ticketDescription': 'Closed repo trader allocation',
  'ticketType': 'Repo Euro Conversions'},
 'KAR': {'ticketDescription': 'Closed repo allocation cash ticket',
  'ticketType': 'Repos'},
 'KMR': {'ticketDescription': 'Closed master repo cash ticket',
  'ticketType': 'Repos'},
 'KP': {'ticketDescription': 'Closed product type allocation',
  'ticketType': 'Repo Euro Conversions'},
 'LT': {'ticketDescription': 'Trader ticket from LATT function',
  'ticketType': 'LATT Transfers'},
 'MAT': {'ticketDescription': 'Trading: maturity P&L', 'ticketType': 'Other'},
 'MC': {'ticketDescription': 'Money-market commitment',
  'ticketType': 'Money Markets'},
 'MCST': {'ticketDescription': 'Completed money-market commitment buy slate',
  'ticketType': 'Money Markets'},
 'MPY': {'ticketDescription': 'Portfolio: mortgage prepay ticket',
  'ticketType': 'Mortgage / TBAs'},
 'MRC': {'ticketDescription': 'Master repo cash ticket',
  'ticketType': 'Repos'},
 'MS': {'ticketDescription': 'Money-market commitment buy slate',
  'ticketType': 'Money Markets'},
 'MSPL': {'ticketDescription': 'Trading: mortgage prepay P&L ticket',
  'ticketType': 'Mortgage / TBAs'},
 'MT': {'ticketDescription': 'Matched ticket',
  'ticketType': 'Ticket Matching'},
 'MT*': {'ticketDescription': 'Unallocated or partially unallocated MT',
  'ticketType': 'Ticket Matching'},
 'MTD': {'ticketDescription': 'Portfolio: matured bond/expired future',
  'ticketType': 'Mortgage / TBAs'},
 'MTG': {'ticketDescription': 'Trading: mortgage prepay P&L ticket',
  'ticketType': 'Other'},
 'NCS': {'ticketDescription': 'Near leg FX swap ticket',
  'ticketType': 'Swaps'},
 'OA': {'ticketDescription': 'Order management allocation ticket',
  'ticketType': 'Order Management'},
 'OM': {'ticketDescription': 'Portfolio order management master ticket',
  'ticketType': 'Order Management'},
 'OMO': {'ticketDescription': 'Order management order, master ticket',
  'ticketType': 'Order Management'},
 'PA': {'ticketDescription': 'Portfolio allocation ticket',
  'ticketType': 'Portfolio Allocations'},
 'PAC': {'ticketDescription': 'Post-trade date corrected agency trader ticket',
  'ticketType': 'SSEOMS'},
 'PACX': {'ticketDescription': 'Cancelled PAC', 'ticketType': 'SSEOMS'},
 'PAX': {'ticketDescription': 'Post-trade date cancelled agency trader ticket',
  'ticketType': 'SSEOMS'},
 'PC*': {'ticketDescription': 'Post-trade date partially allocated ticket (XPT)',
  'ticketType': 'Portfolio Allocations'},
 'PCA': {'ticketDescription': 'Post-trade date corrected POOL',
  'ticketType': 'Mortgage / TBAs'},
 'PCB': {'ticketDescription': 'Post-trade corrected sales MT allocation piece',
  'ticketType': 'Sales'},
 'PCC': {'ticketDescription': 'Post-trade corrected corporate action trade',
  'ticketType': 'Corporate Action'},
 'PCE': {'ticketDescription': 'Post-trade corrected Euro ticket',
  'ticketType': 'Euro Conversion'},
 'PCF': {'ticketDescription': 'Post-trade date corrected futures ticket',
  'ticketType': 'Futures'},
 'PCJ': {'ticketDescription': 'Post-trade date corrected journal trade',
  'ticketType': 'Journal Trades'},
 'PCM': {'ticketDescription': 'Post-trade date corrected matched ticket',
  'ticketType': 'Ticket Matching'},
 'PCN': {'ticketDescription': 'Post-trade correction near leg FX swap ticket',
  'ticketType': 'Swaps'},
 'PCP': {'ticketDescription': 'Post-trade date corrected portfolio allocation ticket',
  'ticketType': 'Portfolio Allocations'},
 'PCP*': {'ticketDescription': 'Post-trade date corrected partially allocated ticket',
  'ticketType': 'Portfolio Allocations'},
 'PCS': {'ticketDescription': 'Post-trade corrected converted settled position',
  'ticketType': 'Euro Conversion'},
 'PCT': {'ticketDescription': 'Post-trade date corrected trader ticket',
  'ticketType': 'Trader Tickets'},
 'PCX': {'ticketDescription': 'Post-trade date corrected sales execution',
  'ticketType': 'Auto-Execution'},
 'PE': {'ticketDescription': 'Pending ticket', 'ticketType': 'Auto-Execution'},
 'PFW': {'ticketDescription': 'Post-trade correction far leg FX swap ticket',
  'ticketType': 'Swaps'},
 'PLT': {'ticketDescription': 'Post-trade date corrected LATT ticket',
  'ticketType': 'LATT Transfers'},
 'PM': {'ticketDescription': 'Portfolio master ticket',
  'ticketType': 'Portfolio Allocations'},
 'PM*': {'ticketDescription': 'Partially allocated master ticket',
  'ticketType': 'Portfolio Allocations'},
 'POL': {'ticketDescription': 'Mortgage pool transaction (completed TBA)',
  'ticketType': 'Mortgage / TBAs'},
 'PPOL': {'ticketDescription': 'Mortgage pool transaction (partial TBA)',
  'ticketType': 'Mortgage / TBAs'},
 'PTB': {'ticketDescription': 'Post-trade date cancelled CTB',
  'ticketType': 'Mortgage / TBAs'},
 'PX*': {'ticketDescription': 'Post-trade cancelled partially allocated ticket (XPT)',
  'ticketType': 'Portfolio Allocations'},
 'PXA': {'ticketDescription': 'Post-trade date cancelled POOL',
  'ticketType': 'Mortgage / TBAs'},
 'PXB': {'ticketDescription': 'Post-trade cancelled sales MT allocation piece',
  'ticketType': 'Sales'},
 'PXC': {'ticketDescription': 'Post-trade cancelled corporate action trade',
  'ticketType': 'Corporate Action'},
 'PXE': {'ticketDescription': 'Post-trade cancelled Euro ticket',
  'ticketType': 'Euro Conversion'},
 'PXF': {'ticketDescription': 'Post-trade date cancelled futures ticket',
  'ticketType': 'Futures'},
 'PXJ': {'ticketDescription': 'Post-trade date corrected journal trade',
  'ticketType': 'Journal Trades'},
 'PXL': {'ticketDescription': 'Post-trade date cancelled LATT ticket',
  'ticketType': 'LATT Transfers'},
 'PXM': {'ticketDescription': 'Post-trade date cancelled matched ticket',
  'ticketType': 'Ticket Matching'},
 'PXN': {'ticketDescription': 'Post-trade cancelled near leg FX swap ticket',
  'ticketType': 'Swaps'},
 'PXP': {'ticketDescription': 'Post-trade date cancelled portfolio allocation ticket',
  'ticketType': 'Portfolio Allocations'},
 'PXP*': {'ticketDescription': 'Post-trade cancelled partially allocated ticket',
  'ticketType': 'Portfolio Allocations'},
 'PXS': {'ticketDescription': 'Post-trade cancelled converted settled position',
  'ticketType': 'Euro Conversion'},
 'PXT': {'ticketDescription': 'Post-trade date cancelled trader ticket',
  'ticketType': 'Trader Tickets'},
 'PXW': {'ticketDescription': 'Post-trade cancelled far leg FX swap ticket',
  'ticketType': 'Swaps'},
 'PXX': {'ticketDescription': 'Post-trade date cancelled sales execution',
  'ticketType': 'Auto-Execution'},
 'RA': {'ticketDescription': 'Repo trader allocation',
  'ticketType': 'Repo Euro Conversions'},
 'REJ': {'ticketDescription': 'Rejected sales ticket', 'ticketType': 'Sales'},
 'RF': {'ticketDescription': 'Retail feed',
  'ticketType': 'Consolidate Message Feed'},
 'RPE': {'ticketDescription': 'Rejected auto-ex ticket',
  'ticketType': 'Auto-Execution'},
 'RPO': {'ticketDescription': 'Repo reverse trades', 'ticketType': 'Repos'},
 'RS': {'ticketDescription': 'Repo money slate', 'ticketType': 'Repos'},
 'RSM': {'ticketDescription': 'Repo sales master ticket',
  'ticketType': 'Repos'},
 'RSO': {'ticketDescription': 'Routed sales order', 'ticketType': 'SSEOMS'},
 'RSP': {'ticketDescription': 'Reinstate settled position in Euro',
  'ticketType': 'Euro Conversion'},
 'RST': {'ticketDescription': 'Repo sales ticket', 'ticketType': 'Repos'},
 'RT': {'ticketDescription': 'Repo ticket with collateral',
  'ticketType': 'Repos'},
 'S': {'ticketDescription': 'Slate', 'ticketType': 'Slates'},
 'S1': {'ticketDescription': 'First leg of repo-euro sales',
  'ticketType': 'Repo Euro Conversions'},
 'SA': {'ticketDescription': 'Sales allocation ticket', 'ticketType': 'Sales'},
 'SB': {'ticketDescription': 'Sales MT allocation piece',
  'ticketType': 'Sales'},
 'SB*': {'ticketDescription': 'Partial sell-buyback master ticket',
  'ticketType': 'Repos'},
 'SBA': {'ticketDescription': 'Sell-buyback allocation',
  'ticketType': 'Repos'},
 'SM': {'ticketDescription': 'Sales master ticket', 'ticketType': 'Sales'},
 'SM*': {'ticketDescription': 'Partial sales master ticket',
  'ticketType': 'Sales'},
 'SO': {'ticketDescription': 'Sellside sales order', 'ticketType': 'SSEOMS'},
 'ST': {'ticketDescription': 'Sales ticket', 'ticketType': 'Sales'},
 'STK': {'ticketDescription': 'Strip ticket', 'ticketType': 'Other'},
 'SWP': {'ticketDescription': 'Cash added/removed from portfolio ',
  'ticketType': 'Cash'},
 'TBA': {'ticketDescription': 'Mortage TBA ticket',
  'ticketType': 'Mortgage / TBAs'},
 'TBAO': {'ticketDescription': 'Mortage TBA offset (partial completed TBA)',
  'ticketType': 'Mortgage / TBAs'},
 'TT': {'ticketDescription': 'Trader ticket', 'ticketType': 'Trader Tickets'},
 'WT': {'ticketDescription': 'Web feed tickets', 'ticketType': 'Other'},
 'XAE': {'ticketDescription': 'Cancelled auto sales execution',
  'ticketType': 'Auto-Execution'},
 'XAP': {'ticketDescription': 'Cancelled repo product type allocation ticket',
  'ticketType': 'Repo Euro Conversions'},
 'XAR': {'ticketDescription': 'Cancelled repo allocation cash ticket',
  'ticketType': 'Repos'},
 'XAT': {'ticketDescription': 'Cancelled agency trader ticket',
  'ticketType': 'SSEOMS'},
 'XBS': {'ticketDescription': 'Cancel of buy-sellback master ticket',
  'ticketType': 'Repos'},
 'XBS*': {'ticketDescription': 'Cancel of sell-buyback master ticket',
  'ticketType': 'Repos'},
 'XBSA': {'ticketDescription': 'Cancel of buy-sellback allocation',
  'ticketType': 'Repos'},
 'XCA': {'ticketDescription': 'Cancelled corporate action trade',
  'ticketType': 'Corporate Action'},
 'XCB': {'ticketDescription': 'Cancelled PCB', 'ticketType': 'Sales'},
 'XCC': {'ticketDescription': 'Cancelled cash compensation transaction',
  'ticketType': 'Euro Conversion'},
 'XCM': {'ticketDescription': 'Cancelled closed repo slate ticket',
  'ticketType': 'Repos'},
 'XCMS': {'ticketDescription': 'Cancelled corrected money-market commitment buy slate',
  'ticketType': 'Money Markets'},
 'XCN': {'ticketDescription': 'Cancelled near leg FX swap ticket',
  'ticketType': 'Swaps'},
 'XCP': {'ticketDescription': 'Cancelled PCP',
  'ticketType': 'Portfolio Allocations'},
 'XCR': {'ticketDescription': 'Cancelled closed repo ticket',
  'ticketType': 'Repos'},
 'XCSJ': {'ticketDescription': 'Cancelled closeout journal ticket',
  'ticketType': 'Swaps'},
 'XCST': {'ticketDescription': 'Cancelled completed money-market commitment buy slate',
  'ticketType': 'Money Markets'},
 'XCSW': {'ticketDescription': 'Cancelled closeout swap ticket',
  'ticketType': 'Swaps'},
 'XCT': {'ticketDescription': 'Cancelled cash ticket from portfolio',
  'ticketType': 'Cash'},
 'XE2': {'ticketDescription': 'Cancelled repo-euro',
  'ticketType': 'Repo Euro Conversions'},
 'XEU': {'ticketDescription': 'Cancelled Euro ticket',
  'ticketType': 'Euro Conversion'},
 'XEX': {'ticketDescription': 'Cancelled sales execution',
  'ticketType': 'Auto-Execution'},
 'XFS': {'ticketDescription': 'Cancelled far leg FX swap ticket',
  'ticketType': 'Swaps'},
 'XFT': {'ticketDescription': 'Cancelled futures ticket',
  'ticketType': 'Futures'},
 'XJL': {'ticketDescription': 'Cancelled journal trade',
  'ticketType': 'Journal Trades'},
 'XKA': {'ticketDescription': 'Cancelled closed repo trader allocation',
  'ticketType': 'Repo Euro Conversions'},
 'XKB': {'ticketDescription': 'Cancelled closed repo allocation cash ticket',
  'ticketType': 'Repos'},
 'XKM': {'ticketDescription': 'Cancelled closed master cash ticket',
  'ticketType': 'Repos'},
 'XKP': {'ticketDescription': 'Cancelled closed product type allocation',
  'ticketType': 'Repo Euro Conversions'},
 'XLA': {'ticketDescription': 'Cancelled of legacy master repo sales',
  'ticketType': 'Repo Euro Conversions'},
 'XLG': {'ticketDescription': 'Cancelled alleged trade',
  'ticketType': 'SSEOMS'},
 'XLR': {'ticketDescription': 'Cancelled legacy repo ticket',
  'ticketType': 'Repo Euro Conversions'},
 'XLS': {'ticketDescription': 'Cancelled of legacy repo sales',
  'ticketType': 'Repo Euro Conversions'},
 'XLT': {'ticketDescription': 'Cancelled LATT ticket',
  'ticketType': 'LATT Transfers'},
 'XMR': {'ticketDescription': 'Cancelled repo master cash ticket',
  'ticketType': 'Repos'},
 'XMS': {'ticketDescription': 'Cancelled money-market commitment buy slate',
  'ticketType': 'Money Markets'},
 'XMT': {'ticketDescription': 'Cancelled matched ticket',
  'ticketType': 'Ticket Matching'},
 'XNC': {'ticketDescription': 'Cancellation of ticket in national currency',
  'ticketType': 'Euro Conversion'},
 'XOMO': {'ticketDescription': 'Cancelled order management order, master ticket',
  'ticketType': 'Order Management'},
 'XOS': {'ticketDescription': 'Cancelled corrected carry-over slate',
  'ticketType': 'Slates'},
 'XOT': {'ticketDescription': 'Cancelled carry-over sales ticket',
  'ticketType': 'Sales'},
 'XP': {'ticketDescription': 'Cancelled portfolio master ticket',
  'ticketType': 'Portfolio Allocations'},
 'XPA': {'ticketDescription': 'Cancelled PCA', 'ticketType': 'Auto-Execution'},
 'XPC': {'ticketDescription': 'Cancelled PCC',
  'ticketType': 'Corporate Action'},
 'XPE': {'ticketDescription': 'Cancelled pending ticket',
  'ticketType': 'Auto-Execution'},
 'XPF': {'ticketDescription': 'Cancelled PCF', 'ticketType': 'Futures'},
 'XPJ': {'ticketDescription': 'Post-trade date cancelled journal trade',
  'ticketType': 'Journal Trades'},
 'XPL': {'ticketDescription': 'Cancelled mortgage pool (from completed TBA)',
  'ticketType': 'Mortgage / TBAs'},
 'XPM': {'ticketDescription': 'Cancelled PCM',
  'ticketType': 'Ticket Matching'},
 'XPN': {'ticketDescription': 'Cancelled PCN', 'ticketType': 'Swaps'},
 'XPO': {'ticketDescription': 'Cancelled portfolio slate',
  'ticketType': 'Other'},
 'XPP': {'ticketDescription': 'Cancelled PLT', 'ticketType': 'LATT Transfers'},
 'XPT': {'ticketDescription': 'Cancelled PCT', 'ticketType': 'Trader Tickets'},
 'XPW': {'ticketDescription': 'Cancelled PFW', 'ticketType': 'Swaps'},
 'XPX': {'ticketDescription': 'Cancelled PCX', 'ticketType': 'Auto-Execution'},
 'XRA': {'ticketDescription': 'Cancelled repo trader allocation',
  'ticketType': 'Repo Euro Conversions'},
 'XRF': {'ticketDescription': 'Cancelled offline ticket',
  'ticketType': 'Consolidate Message Feed'},
 'XRM': {'ticketDescription': 'Cancelled repo sales master ticket',
  'ticketType': 'Repos'},
 'XRO': {'ticketDescription': 'Ccancelled order routing',
  'ticketType': 'SSEOMS'},
 'XRS': {'ticketDescription': 'Cancelled repo money slate',
  'ticketType': 'Repos'},
 'XRT': {'ticketDescription': 'Cancelled repo ticket with collateral',
  'ticketType': 'Repos'},
 'XS': {'ticketDescription': 'Cancelled slate', 'ticketType': 'Slates'},
 'XSB': {'ticketDescription': 'Cancelled sales MT allocation piece',
  'ticketType': 'Sales'},
 'XSB*': {'ticketDescription': 'Cancel of partial sell-buyback master ticket',
  'ticketType': 'Repos'},
 'XSBA': {'ticketDescription': 'Cancel of sell-buyback allocation',
  'ticketType': 'Repos'},
 'XSM': {'ticketDescription': 'Cancelled sales master ticket',
  'ticketType': 'Sales'},
 'XSO': {'ticketDescription': 'Cancelled sellside sales order',
  'ticketType': 'SSEOMS'},
 'XSP': {'ticketDescription': 'Cancelled converted settled position',
  'ticketType': 'Euro Conversion'},
 'XSR': {'ticketDescription': 'Cancelled repo sales ticket',
  'ticketType': 'Repos'},
 'XST': {'ticketDescription': 'Cancelled sales ticket', 'ticketType': 'Sales'},
 'XTB': {'ticketDescription': 'Cancelled mortgage TBA',
  'ticketType': 'Mortgage / TBAs'},
 'XTT': {'ticketDescription': 'Cancelled trader ticket',
  'ticketType': 'Trader Tickets'},
 'XWT': {'ticketDescription': 'Cancelled web feed tickets',
  'ticketType': 'Other'}}